return {
	"id":null,
	"sale_status_id":null,
	"created_on":null,
	"created_by":null,
	"commission_paid_on":null,
	"sale_account":
	{
		"id":null,
		"state_id":"2",
		"vendor_id":"2",
		"bill_delivery_type_id":"2",
		"bill_payment_type_id":"2",
		"direct_debit_type_id":"1",
		"sale_account_direct_debit_credit_card_id":null,
		"sale_account_direct_debit_credit_card":null,
		"sale_account_direct_debit_bank_account_id":null,
		"sale_account_direct_debit_bank_account":
		{
			"id":null,
			"bank_name":"NAB",
			"bank_bsb":"087777",
			"account_number":"3434343434",
			"account_name":"Bobs Account"
		},
		"external_reference":null,
		"business_name":"Bob the Builder Pty Ltd",
		"trading_name":"",
		"abn":"",
		"acn":"",
		"address_line_1":"17 Builders Lane",
		"address_line_2":"",
		"suburb":"Newtown",
		"postcode":"4555"
	},
	
	"contacts":
	[
		{
			"id":null,
			"created_on":null,
			"contact_title_id":"1",
			"contact_status_id":null,
			"external_reference":null,
			"first_name":"Bob",
			"middle_names":"",
			"last_name":"Builder",
			"position_title":"",
			"username":null,
			"password":null,
			"date_of_birth":"1970-03-02",
			"contact_methods":
			[
				{
					"id":null,
					"contact_method_type_id":1,
					"details":"bob@bb.com.au",
					"is_primary":true
				},
				{
					"id":null,
					"contact_method_type_id":2,
					"details":"0765555555",
					"is_primary":false
				},
				{
					"id":null,
					"contact_method_type_id":4,
					"details":"0405699968",
					"is_primary":false
				},
				{
					"id":null,
					"contact_method_type_id":3,
					"details":"0745323455",
					"is_primary":false
				}
			]
		}
	],
			
	"items":
	[
		{
			"id":null,
			"product_type_module":"Service_Landline",
			"product_id":"512",
			"created_on":null,
			"created_by":null,
			"sale_item_status_id":null,
			"commission_paid_on":null,
			"product_detail":
			{
				"id":null,
				"fnn":"0234567656",
				"is_indial_100":true,
				"has_extension_level_billing":true,
				"landline_type_id":"2",
				"landline_type_details":
				{
					"id":null,
					"company_name":"Bob the Builder Pty Ltd",
					"abn":"71 123 111 946",
					"trading_name":""
				},
				
				"landline_service_address_type_id":null,
				"service_address_type_number":null,
				"service_address_type_suffix":null,
				"service_street_number_start":"55",
				"service_street_number_end":null,
				"service_street_number_suffix":null,
				"service_property_name":null,
				"service_street_name":"Builders",
				"landline_service_street_type_id":"137",
				"landline_service_street_type_suffix_id":null,
				"service_locality":"Newtown",
				"landline_service_state_id":"2",
				"service_postcode":"2333",
				"bill_name":"Bob the Builder Pty Ltd",
				"bill_address_line_1":"17 Builders Lane",
				"bill_address_line_2":"",
				"bill_locality":"Newtown",
				"bill_postcode":"4555"
			}
		}
	],
			
	"notes":
	[
		{
			"id":null,
			"sale_id":null,
			"created_dealer_id":null,
			"created_timestamp":null,
			"content":"sdfsdfsdf"
		},
		{
			"id":null,
			"sale_id":null,
			"created_dealer_id":null,
			"created_timestamp":null,
			"content":"sdfdsfdf"
		}
	],
	"sale_type_id":1
};