<?php

// These are employee permission levels
define("PERMISSION_PUBLIC", 0x01);
define("PERMISSION_ADMIN", 0x9F);
define("PERMISSION_OPERATOR", 0x04);
define("PERMISSION_SALES", 0x08);
define("PERMISSION_ACCOUNTS", 0x10);
define("PERMISSION_RATE_MANAGEMENT", 0x20);
define("PERMISSION_CREDIT_MANAGEMENT", 0x40);
define("PERMISSION_OPERATOR_VIEW", 0x80);
define("PERMISSION_OPERATOR_EXTERNAL", 0x100);
define("PERMISSION_CUSTOMER_GROUP_ADMIN", 0x200);
define("PERMISSION_KB_USER", 0x400);
define("PERMISSION_KB_ADMIN_USER", 0x800);
define("PERMISSION_SALES_ADMIN", 0x1000);
define("PERMISSION_PROPER_ADMIN", 0x2000);
define("PERMISSION_SUPER_ADMIN", 0x7FFFFFFF);
define("PERMISSION_DEBUG", 0x80000000);
define("USER_PERMISSION_GOD", 0x7FFFFFFFFFFF); // This constant is legacy
define("PERMISSION_GOD", 0x7FFFFFFFFFFF);

?>