#!/bin/bash
exec add-apt-repository --yes ppa:ondrej/php5-5.6 &&
    add-apt-repository --yes ppa:duggan/php-56 &&
    apt-get --quiet --quiet update &&
    apt-get --quiet --quiet --yes install \
      php5-cli \
      php5-readline \
      php5-curl \
      libssh2-php \
      php5-mcrypt \
      php5-mysqlnd \
      php5-pgsql \
      php5-xsl;