#!/bin/bash
exec wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - &&
	echo 'deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main' > /etc/apt/sources.list.d/pgdg.list &&
	apt-get --quiet --quiet update &&
	apt-get --quiet --quiet --yes install postgresql-client;