#!/usr/bin/php
<?php
if ($argc == 3)
{
	require_once('buildpages.php');
	$strClass = $argv[1];
	$strObject = $argv[2];
	NewHtmlObject($strClass, $strObject);
}
else
{
	echo 'Not enough arguements', "\n";
}
?>
